openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Requests API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Requests
  description: '[https://developer.salesloft.com/docs/api/requests/](https://developer.salesloft.com/docs/api/requests/)'
paths:
  /data_control/requests/{id}:
    get:
      tags:
      - Requests
      summary: Salesloft Fetch a Request Record
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /data_control/requests:
    get:
      tags:
      - Requests
      summary: Salesloft Retrieve a List of Requests
      parameters:
      - name: sort_by
        in: query
        schema:
          type: string
      - name: sort_direction
        in: query
        schema:
          type: string
      - name: per_page
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: include_paging_counts
        in: query
        schema:
          type: string
      - name: team_id
        in: query
        schema:
          type: string
      - name: request_type
        in: query
        schema:
          type: string
      - name: dry_run
        in: query
        schema:
          type: string
      - name: user_guid
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
