openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Webhook Subscriptions API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Webhook Subscriptions
  description: '[https://developer.salesloft.com/docs/api/webhook-subscriptions/](https://developer.salesloft.com/docs/api/webhook-subscriptions/)'
paths:
  /webhook_subscriptions:
    get:
      tags:
      - Webhook Subscriptions
      summary: Salesloft List Webhook Subscriptions
      parameters:
      - name: enabled
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
      - Webhook Subscriptions
      summary: Salesloft Create a Webhook Subscription
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                event_type: string
                callback_url: string
                callback_token: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /webhook_subscriptions/{id}:
    get:
      tags:
      - Webhook Subscriptions
      summary: Salesloft Fetch a Webhook Subscription
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
      - Webhook Subscriptions
      summary: Salesloft Update a Webhook Subscription
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                enabled: false
                callback_url: ttps://691c-2603-8001-6f01-7b24-b9de-3f23-1c77-4033.ngrok-free.app
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
      - Webhook Subscriptions
      summary: Salesloft Delete a Webhook Subscription
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
