openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Client Credentials Access Token API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Client Credentials Access Token
  description: If you are building a private OAuth app, it's likely easier to use Client Credentials rather than OAuth2.0 refresh tokens. Use the request in this folder to retreive an access_token for your private OAuth app using client credentials. The request includes a Postman script to add the returned access_token as a variable in the collection. To use this token in subsequent requests, adjust the authorization of the request to Bearer Token and add {{client_credentials_token}} in the token field.
paths:
  /oauth/token:
    post:
      tags:
      - Client Credentials Access Token
      summary: Salesloft Retrieve Client Credentials Access Token
      requestBody:
        content: {}
      security:
      - noauthAuth: []
      parameters:
      - name: client_id
        in: query
        schema:
          type: string
        example: '{{client_id}}'
      - name: client_secret
        in: query
        schema:
          type: string
        example: '{{client_secret}}'
      - name: grant_type
        in: query
        schema:
          type: string
        example: client_credentials
      - name: scope
        in: query
        schema:
          type: string
        example: public:all
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
