openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Crm Account Team Members API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Crm Account Team Members
  description: '[https://developers.salesloft.com/docs/api/crm-account-team-members/](https://developers.salesloft.com/docs/api/crm-account-team-members/)'
paths:
  /crm_account_team_members:
    get:
      tags:
      - Crm Account Team Members
      summary: Salesloft List CRM Account Team Members
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
