openapi: 3.0.0
info:
  title: Salesloft Account and Redaction People API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: People
  description: '[https://developer.salesloft.com/docs/api/people/](https://developer.salesloft.com/docs/api/people/)'
paths:
  /people:
    post:
      tags:
      - People
      summary: Salesloft Create a Person
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email_address: string
                secondary_email_adress: string
                personal_email_address: string
                first_name: string
                last_name: string
                phone: string
                phone_extension: string
                mobile_phone: string
                home_phone: string
                linkedin_url: string
                title: string
                city: string
                state: string
                country: string
                work_city: string
                work_state: string
                work_country: string
                person-company_name: string
                person_company_website: string
                person_company_industry: string
                job_seniority: string
                do_not_contact: false
                eu_resident: false
                locale: string
                personal_website: string
                twitter_handle: string
                tags:
                - string
                contact_restrictions:
                - string
                custom_fields: {}
                account_id: 0
                owner_id: 0
                import_id: 0
                person_stage_id: 0
                crm_id_type: string
                crm_d: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
      - People
      summary: Salesloft List People
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /people/{id}:
    get:
      tags:
      - People
      summary: Salesloft Fetch a Person
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
      - People
      summary: Salesloft Update a Person
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email_address: string
                secondary_email_adress: string
                personal_email_address: string
                first_name: string
                last_name: string
                phone: string
                phone_extension: string
                mobile_phone: string
                home_phone: string
                linkedin_url: string
                title: string
                city: string
                state: string
                country: string
                work_city: string
                work_state: string
                work_country: string
                person-company_name: string
                person_company_website: string
                person_company_industry: string
                job_seniority: string
                do_not_contact: false
                eu_resident: false
                locale: string
                personal_website: string
                twitter_handle: string
                tags:
                - string
                contact_restrictions:
                - string
                custom_fields: {}
                account_id: 0
                owner_id: 0
                import_id: 0
                person_stage_id: 0
                crm_id_type: string
                crm_d: string
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /people/199954973:
    get:
      tags:
      - People
      summary: Salesloft Delete a Person
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
