openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Cadences API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Cadences
  description: '[https://developer.salesloft.com/docs/api/cadences/](https://developer.salesloft.com/docs/api/cadences/)'
paths:
  /cadences:
    get:
      tags:
      - Cadences
      summary: Salesloft List Cadences
      parameters:
      - name: ids
        in: query
        schema:
          type: string
      - name: updated_at[gt]
        in: query
        schema:
          type: string
      - name: updated_at[gte]
        in: query
        schema:
          type: string
      - name: updated_at[lt]
        in: query
        schema:
          type: string
      - name: updated_at[lte]
        in: query
        schema:
          type: string
      - name: team_cadence
        in: query
        schema:
          type: string
      - name: shared
        in: query
        schema:
          type: string
      - name: owned_by_guid
        in: query
        schema:
          type: string
      - name: people_addable
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      - name: group_ids
        in: query
        schema:
          type: string
      - name: tag_ids
        in: query
        schema:
          type: string
      - name: archived
        in: query
        schema:
          type: string
      - name: override_contact_restrictions
        in: query
        schema:
          type: string
      - name: pending_actions_assigned_to
        in: query
        schema:
          type: string
      - name: sort_by
        in: query
        schema:
          type: string
      - name: sort_direction
        in: query
        schema:
          type: string
      - name: per_page
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: include_paging_counts
        in: query
        schema:
          type: string
      - name: limit_paging_counts
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /cadences/{id}:
    get:
      tags:
      - Cadences
      summary: Salesloft Fetch a Cadence
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
