openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Bulk Reschedule Tasks API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Bulk Reschedule Tasks
  description: '[https://developer.salesloft.com/docs/api/bulk-reschedule-tasks/](https://developer.salesloft.com/docs/api/bulk-reschedule-tasks/)'
paths:
  /bulk_reschedule_tasks:
    post:
      tags:
      - Bulk Reschedule Tasks
      summary: Salesloft Reschedule Many Tasks at Once
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                task_ids:
                - 0
                - 1
                due_date: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
