openapi: 3.0.0
info:
  title: Salesloft Account and People Redaction Crm Activities API
  description: This data allows integration owners to self-serve and claim more ownership over API usage, especially when using the Signals API to integrate with Rhythm. This ...
  version: 1.0.0
servers:
- url: http://{{salesloft_api_base_url}}
- url: https://accounts.salesloft.com
- url: http://{{salesloft_api_base_url}}external
security:
- oauth2Auth: []
tags:
- name: Crm Activities
  description: '[https://developer.salesloft.com/docs/api/crm-activities/](https://developer.salesloft.com/docs/api/crm-activities/)'
paths:
  /crm_activities:
    get:
      tags:
      - Crm Activities
      summary: Salesloft List Crm Activities
      parameters:
      - name: ids
        in: query
        schema:
          type: string
      - name: updated_at[gt]
        in: query
        schema:
          type: string
      - name: updated_at[gte]
        in: query
        schema:
          type: string
      - name: updated_at[lt]
        in: query
        schema:
          type: string
      - name: updated_at[lte]
        in: query
        schema:
          type: string
      - name: sort_by
        in: query
        schema:
          type: string
      - name: sort_direction
        in: query
        schema:
          type: string
      - name: per_page
        in: query
        schema:
          type: string
      - name: page
        in: query
        schema:
          type: string
      - name: include_paging_counts
        in: query
        schema:
          type: string
      - name: limit_paging_counts
        in: query
        schema:
          type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /crm_activities/{id}:
    get:
      tags:
      - Crm Activities
      summary: Salesloft Fetch a Crm Activity
      parameters:
      - name: id
        in: path
        schema:
          type: string
        required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
    oauth2Auth:
      type: http
      scheme: oauth2
